

$edit_screen_arr =

{
   
    
    "edit_color_red" => {
        
        "White" => 1,
        "Gray" => 0.49,
        "Black" => 0,
        "Light blue" => 0.4,
        "Blue" => 0.4,
        "Purple" => 0.53,
        "Orchid" => 0.87,
        "Pink" => 1,
        "Red" => 1,
        "Orange" => 1,
        "Gold" => 1,
        "Yellow" => 1,
        "Olive" => 0.8,
        "Green" => 0.33,
        "Aquamarin" => 0.33
        
            },
    
    
    "edit_color_blue" => {
        
        "White" => 1,
        "Gray" => 0.49,
        "Black" => 0,
        "Light blue" => 1,
        "Blue" => 1,
        "Purple" => 1,
        "Orchid" => 1,
        "Pink" => 0.8,
        "Red" => 0.53,
        "Orange" => 0.4,
        "Gold" => 0.4,
        "Yellow" => 0.39,
        "Olive" => 0.4,
        "Green" => 0.53,
        "Aquamarin" => 0.92
        
            },
    
    
    "edit_color_green" => {
        
        "White" => 1,
        "Gray" => 0.49,
        "Black" => 0,
        "Light blue" => 0.8,
        "Blue" => 0.53,
        "Purple" => 0.4,
        "Orchid" => 0.4,
        "Pink" => 0.4,
        "Red" => 0.4,
        "Orange" => 0.53,
        "Gold" => 0.8,
        "Yellow" => 0.97,
        "Olive" => 1,
        "Green" => 1,
        "Aquamarin" => 1
        
            }
    }
	
	$sticker ={ 
        'sticker_tab_0' => {
            'sticker_0' => {'name' => 'Flowers Left Sticker','value' =>'Flowers Left Sticker'},
            'sticker_1' => {'name' => 'Flowers Daisies Sticker','value' =>'Flowers Daisies Sticker'},
            'sticker_2' => {'name' => 'Rose Sticker','value' =>'Rose Sticker'},
            'sticker_3' => {'name' => 'Girl Flower Sticker','value' =>'Girl Flower Sticker'},
            'sticker_4' => {'name' => 'Rosebud Leaves Sticker','value' =>'Rosebud Leaves Sticker'},
            'sticker_5' => {'name' => 'Aster Flower Sticker','value' =>'Aster Flower Sticker'},
            #'sticker_6' => {'name' => 'Mother's Day Sticker','value' =>'Mother's Day Sticker'},
            'sticker_6' => {'name' => 'Flower Sticker','value' =>'Flower Sticker'},
            'sticker_7' => {'name' => 'Snails Sticker','value' =>'Snails Sticker'},
            'sticker_8' => {'name' => 'Envelope Sticker','value' =>'Envelope Sticker'},
            'sticker_9' => {'name' => 'Three Flowers Bunch Sticker','value' =>'Three Flowers Bunch Sticker'},
            'sticker_10' => {'name' => 'Envelope Flowers Sticker','value' =>'Envelope Flowers Sticker'},
            'sticker_11' => {'name' => 'Banner Flowers Sticker','value' =>'Banner Flowers Sticker'},
            'sticker_12' => {'name' => 'Heart Mom Sticker','value' =>'Heart Mom Sticker'},
            'sticker_13' => {'name' => 'Mother Giraffe Sticker','value' =>'Mother Giraffe Sticker'},
            'sticker_14' => {'name' => 'Silhoutte Sticker','value' =>'Silhoutte Sticker'},
            'sticker_15' => {'name' => 'Three Daisies Sticker','value' =>'Three Daisies Sticker'},
            'sticker_16' => {'name' => 'Cat Holding Flowers Sticker','value' =>'Cat Holding Flowers Sticker'},
            'sticker_17' => {'name' => 'Banner Flowers 2 Sticker','value' =>'Banner Flowers 2 Sticker'},
            'sticker_18' => {'name' => 'Pacifier Sticker','value' =>'Pacifier Sticker'},
            'sticker_19' => {'name' => 'Mother Turtle Sticker','value' =>'Mother Turtle Sticker'},
            'sticker_20' => {'name' => 'Mom Tattoo Sticker','value' =>'Mom Tattoo Sticker'},
            'sticker_21' => {'name' => 'We Love You Sticker','value' =>'We Love You Sticker'},
            'sticker_22' => {'name' => 'Flowers Right Sticker','value' =>'Flowers Right Sticker'},
            'sticker_23' => {'name' => 'Bouquet Sticker','value' =>'Bouquet Sticker'},
            'sticker_24' => {'name' => 'Feather Color Sticker','value' =>'Feather Color Sticker'},
            'sticker_25' => {'name' => 'Three Rosebuds Sticker','value' =>'Three Rosebuds Sticker'},
            'sticker_26' => {'name' => 'Mom Child Cats Sticker','value' =>'Mom Child Cats Sticker'}
        },

        'sticker_tab_1' => {
            'sticker_0' => {'name' => 'Graduation Glasses Sticker','value' =>'Graduation Glasses Sticker'},
            'sticker_1' => {'name' => 'Graduation Horn Sticker','value' =>'Graduation Horn Sticker'},
            'sticker_2' => {'name' => 'Owl Sticker','value' =>'Owl Sticker'},
            'sticker_3' => {'name' => 'Necktie Graduation Sticker','value' =>'Necktie Graduation Sticker'},
            'sticker_4' => {'name' => 'Ribbon Graduation Sticker','value' =>'Ribbon Graduation Sticker'},
            'sticker_5' => {'name' => 'Cap Sticker','value' =>'Cap Sticker'},
            'sticker_6' => {'name' => 'Medal Sticker','value' =>'Medal Sticker'},
            'sticker_7' => {'name' => 'Nerd Glasses Sticker','value' =>'Nerd Glasses Sticker'},
            'sticker_8' => {'name' => 'Bowtie Graduation Sticker','value' =>'Bowtie Graduation Sticker'},
            'sticker_9' => {'name' => 'Flying Caps Graduation Sticker','value' =>'Flying Caps Graduation Sticker'},
            'sticker_10' => {'name' => 'Diploma Sticker','value' =>'Diploma Sticker'},
            'sticker_11' => {'name' => 'Ribbon Sticker','value' =>'Ribbon Sticker'},
            'sticker_12' => {'name' => 'Cap Graduation Sticker','value' =>'Cap Graduation Sticker'},
            'sticker_13' => {'name' => 'Medal Gratuation Sticker','value' =>'Medal Gratuation Sticker'},
            'sticker_14' => {'name' => 'Graduation Balloons Sticker','value' =>'Graduation Balloons Sticker'},
            'sticker_15' => {'name' => 'Books Sticker','value' =>'Books Sticker'},
            'sticker_16' => {'name' => 'Diploma Doodle Sticker','value' =>'Diploma Doodle Sticker'},
            'sticker_17' => {'name' => 'Book Stack Sticker','value' =>'Book Stack Sticker'},
            'sticker_18' => {'name' => 'Confetti Sticker','value' =>'Confetti Sticker'},
            'sticker_19' => {'name' => 'Pencil Sticker','value' =>'Pencil Sticker'},
            'sticker_20' => {'name' => 'Confetti Graduation Sticker','value' =>'Confetti Graduation Sticker'},
            'sticker_21' => {'name' => 'Pencil Graduation Sticker','value' =>'Pencil Graduation Sticker'}
        },
        'sticker_tab_2' => {
            'sticker_0' => {'name' => 'Aviator Glasses Color Sticker','value' =>'Aviator Glasses Color Sticker'},
            'sticker_1' => {'name' => 'Bunny Ears Flowers Sticker','value' =>'Bunny Ears Flowers Sticker'},
            'sticker_2' => {'name' => 'Rabbit Mask Sticker','value' =>'Rabbit Mask Sticker'},
            'sticker_3' => {'name' => 'Sun Hat Sticker','value' =>'Sun Hat Sticker'},
            'sticker_4' => {'name' => 'Panda Mask Sticker','value' =>'Panda Mask Sticker'},
            'sticker_5' => {'name' => 'Beard Sticker','value' =>'Beard Sticker'},
            'sticker_6' => {'name' => 'Lips Sticker','value' =>'Lips Sticker'},
            'sticker_7' => {'name' => 'Cat Ears Sticker','value' =>'Cat Ears Sticker'},
            'sticker_8' => {'name' => 'Cat Whiskers Sticker','value' =>'Cat Whiskers Sticker'},
            'sticker_9' => {'name' => 'Derby Sticker','value' =>'Derby Sticker'},
            'sticker_10' => {'name' => 'Devil Horns Sticker','value' =>'Devil Horns Sticker'},
            'sticker_11' => {'name' => 'Glasses Football Sticker','value' =>'Glasses Football Sticker'},
            'sticker_12' => {'name' => 'Cat Glasses Sticker','value' =>'Cat Glasses Sticker'},
            'sticker_13' => {'name' => 'Crown Sticker','value' =>'Crown Sticker'},
            'sticker_14' => {'name' => 'Birthday Hat Sticker','value' =>'Birthday Hat Sticker'},
            'sticker_15' => {'name' => 'Glasses Red Sticker','value' =>'Glasses Red Sticker'},
            'sticker_16' => {'name' => 'Sunglasses Sticker','value' =>'Sunglasses Sticker'},
            'sticker_17' => {'name' => 'Glasses 1 Sticker','value' =>'Glasses 1 Sticker'},
            'sticker_18' => {'name' => 'Party Hat Sticker','value' =>'Party Hat Sticker'},
            'sticker_19' => {'name' => 'Glasses Blinds Sticker','value' =>'Glasses Blinds Sticker'},
            'sticker_20' => {'name' => 'Mustache Brown Sticker','value' =>'Mustache Brown Sticker'},
            'sticker_21' => {'name' => 'Glasses Sticker','value' =>'Glasses Sticker'},
            'sticker_22' => {'name' => 'Aviator Glasses Sticker','value' =>'Aviator Glasses Sticker'},
            'sticker_23' => {'name' => 'Glasses Blossom Sticker','value' =>'Glasses Blossom Sticker'},
            'sticker_24' => {'name' => 'Cat on Head Sticker','value' =>'Cat on Head Sticker'},
            'sticker_25' => {'name' => 'Mustache Dark Sticker','value' =>'Mustache Dark Sticker'}
        },
        'sticker_tab_3' => {
            'sticker_0' => {'name' => 'Heart Garland Sticker','value' =>'Heart Garland Sticker'},
            'sticker_1' => {'name' => 'Stars Bunch Sticker','value' =>'Stars Bunch Sticker'},
            'sticker_2' => {'name' => '3D diamond 2 Sticker','value' =>'3D diamond 2 Sticker'},
            'sticker_3' => {'name' => 'Unicorn Sticker','value' =>'Unicorn Sticker'},
            'sticker_4' => {'name' => 'Heart Arrow Sticker','value' =>'Heart Arrow Sticker'},
            'sticker_5' => {'name' => 'Skull Sticker','value' =>'Skull Sticker'},
            'sticker_6' => {'name' => 'Hearts Sticker','value' =>'Hearts Sticker'},
            'sticker_7' => {'name' => 'Xoxo Sticker','value' =>'Xoxo Sticker'},
            'sticker_8' => {'name' => 'Feather Sticker','value' =>'Feather Sticker'},
            'sticker_9' => {'name' => 'Heart Wings Sticker','value' =>'Heart Wings Sticker'},
            'sticker_10' => {'name' => 'Arrow Sticker','value' =>'Arrow Sticker'},
            'sticker_11' => {'name' => 'LOL Sticker','value' =>'LOL Sticker'},
            'sticker_12' => {'name' => 'Heart 2 Sticker','value' =>'Heart 2 Sticker'},
            'sticker_13' => {'name' => 'Diamond Sticker','value' =>'Diamond Sticker'},
            'sticker_14' => {'name' => 'Peace Sticker','value' =>'Peace Sticker'},
            'sticker_15' => {'name' => 'Smiley Sticker','value' =>'Smiley Sticker'},
            'sticker_16' => {'name' => 'Feather 2 Sticker','value' =>'Feather 2 Sticker'},
            'sticker_17' => {'name' => 'OMG Sticker','value' =>'OMG Sticker'},
            'sticker_18' => {'name' => 'Hearts Doodle Sticker','value' =>'Hearts Doodle Sticker'},
            'sticker_19' => {'name' => 'Banner Sticker','value' =>'Banner Sticker'},
            'sticker_20' => {'name' => 'Thumbs Up Sticker','value' =>'Thumbs Up Sticker'},
            'sticker_21' => {'name' => 'Heart Sticker','value' =>'Heart Sticker'},
            'sticker_22' => {'name' => 'Football Sticker','value' =>'Football Sticker'},
            'sticker_23' => {'name' => 'Heart Express Sticker','value' =>'Heart Express Sticker'},
            'sticker_24' => {'name' => '3D diamond 1 Sticker','value' =>'3D diamond 1 Sticker'},
            'sticker_25' => {'name' => 'Fist Sticker','value' =>'Fist Sticker'},
            'sticker_26' => {'name' => 'Heart Pixel Sticker','value' =>'Heart Pixel Sticker'},
            'sticker_27' => {'name' => 'Word Cloud Grumble Sticker','value' =>'Word Cloud Grumble Sticker'}
        },
        'sticker_tab_4' => {
            'sticker_0' => {'name' => 'Frappuccino Sticker','value' =>'Frappuccino Sticker'},
            'sticker_1' => {'name' => 'Pineapple Sticker','value' =>'Pineapple Sticker'},
            'sticker_2' => {'name' => 'Cupcake Sticker','value' =>'Cupcake Sticker'},
            'sticker_3' => {'name' => 'Cat Fries Sticker','value' =>'Cat Fries Sticker'},
            'sticker_4' => {'name' => 'BBQ Sticker','value' =>'BBQ Sticker'},
            'sticker_5' => {'name' => 'Pie Sticker','value' =>'Pie Sticker'},
            'sticker_6' => {'name' => 'Doughnut Sticker','value' =>'Doughnut Sticker'},
            'sticker_7' => {'name' => 'Bacon n egg Sticker','value' =>'Bacon n egg Sticker'},
            'sticker_8' => {'name' => 'Sundae Sticker','value' =>'Sundae Sticker'},
            'sticker_9' => {'name' => 'Ketchup Hot Dog Sticker','value' =>'Ketchup Hot Dog Sticker'},
            'sticker_10' => {'name' => 'Soda Sticker','value' =>'Soda Sticker'},
            'sticker_11' => {'name' => 'Pizza Sticker','value' =>'Pizza Sticker'},
            'sticker_12' => {'name' => 'Soda Can Sticker','value' =>'Soda Can Sticker'},
            'sticker_13' => {'name' => 'Valentines Cupcake Sticker','value' =>'Valentines Cupcake Sticker'},
            'sticker_14' => {'name' => 'Apple Angry Sticker','value' =>'Apple Angry Sticker'},
            'sticker_15' => {'name' => 'Turkey Sticker','value' =>'Turkey Sticker'},
            'sticker_16' => {'name' => 'Taco 2 Sticker','value' =>'Taco 2 Sticker'},
            'sticker_17' => {'name' => 'Ice Cream Cone Sticker','value' =>'Ice Cream Cone Sticker'},
            'sticker_18' => {'name' => 'Ice Cream Tub Sticker','value' =>'Ice Cream Tub Sticker'},
            'sticker_19' => {'name' => 'Spoon Sticker','value' =>'Spoon Sticker'},
            'sticker_20' => {'name' => 'Cocoa Sticker','value' =>'Cocoa Sticker'},
            'sticker_21' => {'name' => 'Watermelon Sticker','value' =>'Watermelon Sticker'},
            'sticker_22' => {'name' => 'Candy Sticker','value' =>'Candy Sticker'},
            'sticker_23' => {'name' => 'Cat Coffee Sticker','value' =>'Cat Coffee Sticker'},
            'sticker_24' => {'name' => 'Fork Sticker','value' =>'Fork Sticker'},
            'sticker_25' => {'name' => 'Oranges Sticker','value' =>'Oranges Sticker'}
        },
        'sticker_tab_5' => {
            'sticker_0' => {'name' => 'Balloons 2 Sticker','value' =>'Balloons 2 Sticker'},
            'sticker_1' => {'name' => 'Cupcake Sticker','value' =>'Cupcake Sticker'},
            'sticker_2' => {'name' => 'Party Hat Sticker','value' =>'Party Hat Sticker'},
            'sticker_3' => {'name' => 'Banner Sticker','value' =>'Banner Sticker'},
            'sticker_4' => {'name' => 'Fireworks Sticker','value' =>'Fireworks Sticker'},
            'sticker_5' => {'name' => 'Stars Sticker','value' =>'Stars Sticker'},
            'sticker_6' => {'name' => 'Birthday Hat Sticker','value' =>'Birthday Hat Sticker'},
            'sticker_7' => {'name' => 'Gift Sticker','value' =>'Gift Sticker'},
            'sticker_8' => {'name' => 'Balloons Sticker','value' =>'Balloons Sticker'},
            'sticker_9' => {'name' => 'Cake Sticker','value' =>'Cake Sticker'},
            'sticker_10' => {'name' => 'Gift Dog Sticker','value' =>'Gift Dog Sticker'},
            'sticker_11' => {'name' => 'Cat Celebrate Sticker','value' =>'Cat Celebrate Sticker'},
            'sticker_12' => {'name' => 'Crown Sticker','value' =>'Crown Sticker'},
            'sticker_13' => {'name' => 'Horn Sticker','value' =>'Horn Sticker'}
        },
        'sticker_tab_6' => {
            'sticker_0' => {'name' => 'Cat Face Sticker','value' =>'Cat Face Sticker'},
            'sticker_1' => {'name' => 'Fox Sticker','value' =>'Fox Sticker'},
            'sticker_2' => {'name' => 'Rabbit Sticker','value' =>'Rabbit Sticker'},
            'sticker_3' => {'name' => 'Cat Fries Sticker','value' =>'Cat Fries Sticker'},
            'sticker_4' => {'name' => 'Cat Sticker','value' =>'Cat Sticker'},
            'sticker_5' => {'name' => 'Hedgehog Sticker','value' =>'Hedgehog Sticker'},
            'sticker_6' => {'name' => 'Scary Cat Sticker','value' =>'Scary Cat Sticker'},
            'sticker_7' => {'name' => 'Spider Sticker','value' =>'Spider Sticker'},
            'sticker_8' => {'name' => 'Dog Sticker','value' =>'Dog Sticker'},
            'sticker_9' => {'name' => 'Owl Sticker','value' =>'Owl Sticker'},
            'sticker_10' => {'name' => 'Cat on Head Sticker','value' =>'Cat on Head Sticker'},
            'sticker_11' => {'name' => 'Bird Envelope Sticker','value' =>'Bird Envelope Sticker'},
            'sticker_12' => {'name' => 'Sloth Sticker','value' =>'Sloth Sticker'},
            'sticker_13' => {'name' => 'Panda Sticker','value' =>'Panda Sticker'},
            'sticker_14' => {'name' => 'Cat Shock Sticker','value' =>'Cat Shock Sticker'},
            'sticker_15' => {'name' => 'Butterfly Sticker','value' =>'Butterfly Sticker'},
            'sticker_16' => {'name' => 'Bird Sticker','value' =>'Bird Sticker'},
            'sticker_17' => {'name' => 'Koala Sticker','value' =>'Koala Sticker'},
            'sticker_18' => {'name' => 'Cat Grumble Sticker','value' =>'Cat Grumble Sticker'},
            'sticker_19' => {'name' => 'Pig Sticker','value' =>'Pig Sticker'}
        },
         'sticker_tab_7' => {
            'sticker_0' => {'name' => 'Feather Sticker','value' =>'Feather Sticker'},
            'sticker_1' => {'name' => 'Rainbow 2 Sticker','value' =>'Rainbow 2 Sticker'},
            'sticker_2' => {'name' => 'Flowers Sticker','value' =>'Flowers Sticker'},
            'sticker_3' => {'name' => 'Moon Sticker','value' =>'Moon Sticker'},
            'sticker_4' => {'name' => 'Feather 2 Sticker','value' =>'Feather 2 Sticker'},
            'sticker_5' => {'name' => 'Hibiscus Sticker','value' =>'Hibiscus Sticker'},
            'sticker_6' => {'name' => 'Sun Sticker','value' =>'Sun Sticker'},
            'sticker_7' => {'name' => 'Heart Bouquet Sticker','value' =>'Heart Bouquet Sticker'},
            'sticker_8' => {'name' => 'Mushrooms Sticker','value' =>'Mushrooms Sticker'},
            'sticker_9' => {'name' => 'Flowers Sticker','value' =>'Flowers Sticker'},
            'sticker_10' => {'name' => 'Plum Blossom Sticker','value' =>'Plum Blossom Sticker'},
            'sticker_11' => {'name' => 'Sun Face Sticker','value' =>'Sun Face Sticker'},
            'sticker_12' => {'name' => 'Star Sticker','value' =>'Star Sticker'},
            'sticker_13' => {'name' => 'Cloud Sun Sticker','value' =>'Cloud Sun Sticker'},
            'sticker_14' => {'name' => 'Leaves Sticker','value' =>'Leaves Sticker'},
            'sticker_15' => {'name' => 'Rosebud Sticker','value' =>'Rosebud Sticker'},
            'sticker_16' => {'name' => 'Palm Tree Sticker','value' =>'Palm Tree Sticker'},
            'sticker_17' => {'name' => 'Stars Sticker','value' =>'Stars Sticker'},
            'sticker_18' => {'name' => 'Cloud Angry Sticker','value' =>'Cloud Angry Sticker'},
            'sticker_19' => {'name' => 'Palm Tree 2 Sticker','value' =>'Palm Tree 2 Sticker'},
            'sticker_20' => {'name' => 'Wave Sticker','value' =>'Wave Sticker'},
            'sticker_21' => {'name' => 'Star Yellow Sticker','value' =>'Star Yellow Sticker'},
            'sticker_22' => {'name' => 'Cloud Sad Sticker','value' =>'Cloud Sad Sticker'}
        },
        'sticker_tab_8' => {
            'sticker_0' => {'name' => 'Band aid 2 Sticker','value' =>'Band aid 2 Sticker'},
            'sticker_1' => {'name' => 'Letter Sticker','value' =>'Letter Sticker'},
            'sticker_2' => {'name' => 'Kleenex Sticker','value' =>'Kleenex Sticker'},
            'sticker_3' => {'name' => 'Measles Sticker','value' =>'Measles Sticker'},
            'sticker_4' => {'name' => 'Medicine Sticker','value' =>'Medicine Sticker'},
            'sticker_5' => {'name' => 'Love Monster Sticker','value' =>'Love Monster Sticker'}
        }

          }

           $frame ={ 
            'frame_0' => {'name' => 'Hearts Overlay Frame','value' =>'HeartsOverlayFrame'},
            'frame_1' => {'name' => 'Sloppy Frame','value' =>'SloppyFrame'},
            'frame_2' => {'name' => 'Rainbow Frame','value' =>'RainbowFrame'},
            'frame_3' => {'name' => 'White Frame','value' =>'WhiteFrame'},
            'frame_4' => {'name' => 'Stars Overlay Frame','value' =>'StarsOverlayFrame'},
            'frame_5' => {'name' => 'Polka Dots Frame','value' =>'PolkadotsFrame'},
            'frame_6' => {'name' => 'Grey Shadow Frame','value' =>'GreyShadowFrame'},
            'frame_7' => {'name' => 'Pink Triangle Frame','value' =>'PinkTriangleFrame'},
            'frame_8' => {'name' => 'White Rounded Frame','value' =>'WhiteRoundedFrame'},
            'frame_9' => {'name' => 'Floral 2 Frame','value' =>'Floral2Frame'},
            'frame_10' => {'name' => 'Blue Watercolor Frame','value' =>'BlueWatercoloFrame'},
            'frame_11' => {'name' => 'Floral Overlay Frame','value' =>'FloralOverlayFrame'},
            'frame_12' => {'name' => 'Red Frame','value' =>'RedFrame'},
            'frame_13' => {'name' => 'Gradient Frame','value' =>'GradientFrame'},
            'frame_14' => {'name' => 'Turquoise Frame','value' =>'TurquoiseFrame'},
            'frame_15' => {'name' => 'Dots Overlay Frame','value' =>'DotsOverlayFrame'},
            'frame_16' => {'name' => 'Kraft Frame','value' =>'KraftFrame'},
            'frame_17' => {'name' => 'White Bar Frame','value' =>'WhiteBarFrame'},
            'frame_18' => {'name' => 'Pink Spray Paint Frame','value' =>'PinkSpraypaintFrame'},
            'frame_19' => {'name' => 'White Full Frame','value' =>'WhiteFullFrame'}
        }
        $font ={ 
            'font_0' => {'name' => 'Aleo','value' =>'Aleo'},
            'font_1' => {'name' => 'BERNIER Regular','value' =>'BERNIERRegular-Regular'},
            'font_2' => {'name' => 'Blogger Sans','value' =>'BloggerSans-Light'},
            'font_3' => {'name' => 'Cheque','value' =>'Cheque-Regular'},
            'font_4' => {'name' => 'Fira Sans','value' =>'FiraSans-Regular'},
            'font_5' => {'name' => 'Gagalin','value' =>'Gagalin-Regular'},
            'font_6' => {'name' => 'Hagin Caps Thin','value' =>'Hagin'},
            'font_7' => {'name' => 'Panton','value' =>'Panton-LightitalicCaps'},
            'font_8' => {'name' => 'Panton','value' =>'Panton-LightitalicCaps'},
            'font_9' => {'name' => 'Perfograma','value' =>'Perfograma'},
            'font_10' => {'name' => 'Summer Font','value' =>'SummerFont-Light'},
            'font_11' => {'name' => 'American Typewriter','value' =>'American'},
            'font_12' => {'name' => 'Baskerville','value' =>'Baskerville'},
            'font_13' => {'name' => 'Bodoni 72','value' =>'BodoniSvtyTwoITCTT-Book'},
            'font_14' => {'name' => 'Bradley Hand','value' =>'Bradley'},
            'font_15' => {'name' => 'Chalkboard SE','value' =>'ChalkboardSE-Regular'},
            'font_16' => {'name' => 'DIN Alternate','value' =>'DIN'},
            'font_17' => {'name' => 'Helvetica Neue','value' =>'Helvetica'},
            'font_18' => {'name' => 'Noteworthy','value' =>'Noteworthy-Light'},
            'font_19' => {'name' => 'Snell Roundhand','value' =>'Snell'},
            'font_20' => {'name' => 'Thonburi','value' =>'Thonburi'}
                             
        }