

$edit_screen_arr =

    {


        "edit_color_red" => {

            "White" => 1,
            "Gray" => 0.49,
            "Black" => 0,
            "Light blue" => 0.4,
            "Blue" => 0.4,
            "Purple" => 0.53,
            "Orchid" => 0.87,
            "Pink" => 1,
            "Red" => 1,
            "Orange" => 1,
            "Gold" => 1,
            "Yellow" => 1,
            "Olive" => 0.8,
            "Green" => 0.33,
            "Aquamarin" => 0.33

        },


        "edit_color_blue" => {

            "White" => 1,
            "Gray" => 0.49,
            "Black" => 0,
            "Light blue" => 1,
            "Blue" => 1,
            "Purple" => 1,
            "Orchid" => 1,
            "Pink" => 0.8,
            "Red" => 0.53,
            "Orange" => 0.4,
            "Gold" => 0.4,
            "Yellow" => 0.39,
            "Olive" => 0.4,
            "Green" => 0.53,
            "Aquamarin" => 0.92

        },


        "edit_color_green" => {

            "White" => 1,
            "Gray" => 0.49,
            "Black" => 0,
            "Light blue" => 0.8,
            "Blue" => 0.53,
            "Purple" => 0.4,
            "Orchid" => 0.4,
            "Pink" => 0.4,
            "Red" => 0.4,
            "Orange" => 0.53,
            "Gold" => 0.8,
            "Yellow" => 0.97,
            "Olive" => 1,
            "Green" => 1,
            "Aquamarin" => 1

        }
    }

$sticker ={
    'sticker_tab_0' => {
        'sticker_0' => {'name' => 'Graduation Glasses Sticker','value' =>'Graduation Glasses Sticker'},
        'sticker_1' => {'name' => 'Graduation Horn Sticker','value' =>'Graduation Horn Sticker'},
        'sticker_2' => {'name' => 'Owl Sticker','value' =>'Owl Sticker'},
        'sticker_3' => {'name' => 'Necktie Graduation Sticker','value' =>'Necktie Graduation Sticker'},
        'sticker_4' => {'name' => 'Ribbon Graduation Sticker','value' =>'Ribbon Graduation Sticker'},
        'sticker_5' => {'name' => 'Cap Sticker','value' =>'Cap Sticker'},
        'sticker_6' => {'name' => 'Medal Sticker','value' =>'Medal Sticker'},
        'sticker_7' => {'name' => 'Nerd Glasses Sticker','value' =>'Nerd Glasses Sticker'},
        'sticker_8' => {'name' => 'Bowtie Graduation Sticker','value' =>'Bowtie Graduation Sticker'},
        'sticker_9' => {'name' => 'Flying Caps Graduation Sticker','value' =>'Flying Caps Graduation Sticker'},
        'sticker_10' => {'name' => 'Diploma Sticker','value' =>'Diploma Sticker'},
        'sticker_11' => {'name' => 'Ribbon Sticker','value' =>'Ribbon Sticker'},
        'sticker_12' => {'name' => 'Cap Graduation Sticker','value' =>'Cap Graduation Sticker'},
        'sticker_13' => {'name' => 'Medal Gratuation Sticker','value' =>'Medal Gratuation Sticker'},
        'sticker_14' => {'name' => 'Graduation Balloons Sticker','value' =>'Graduation Balloons Sticker'},
        'sticker_15' => {'name' => 'Books Sticker','value' =>'Books Sticker'},
        'sticker_16' => {'name' => 'Diploma Doodle Sticker','value' =>'Diploma Doodle Sticker'},
        'sticker_17' => {'name' => 'Book Stack Sticker','value' =>'Book Stack Sticker'},
        'sticker_18' => {'name' => 'Confetti Sticker','value' =>'Confetti Sticker'},
        'sticker_19' => {'name' => 'Pencil Sticker','value' =>'Pencil Sticker'},
        'sticker_20' => {'name' => 'Confetti Graduation Sticker','value' =>'Confetti Graduation Sticker'},
        'sticker_21' => {'name' => 'Pencil Graduation Sticker','value' =>'Pencil Graduation Sticker'}
    },
    'sticker_tab_1' => {
        'sticker_0' => {'name' => 'Flower Glasses Sticker','value' => 'Flower Glasses Sticker'},
        'sticker_1' => {'name' => 'Pineapple Sticker','value' => 'Pineapple Sticker'},
        'sticker_2' => {'name' => 'Hibiscus Sticker','value' => 'Hibiscus Sticker'},
        'sticker_3' => {'name' => 'Radio Sticker','value' => 'Radio Sticker'},
        'sticker_4' => {'name' => 'Aviator Glasses Sticker','value' => 'Aviator Glasses Sticker'},
        'sticker_5' => {'name' => 'Beachball Sticker','value' => 'Beachball Sticker'},
        'sticker_6' => {'name' => 'Bike Cruiser Sticker','value' => 'Bike Cruiser Sticker'},
        'sticker_7' => {'name' => 'Sunglasses Palmtree Sticker','value' => 'Sunglasses Palmtree Sticker'},
        'sticker_8' => {'name' => 'Popsicle Green Sticker','value' => 'Popsicle Green Sticker'},
        'sticker_9' => {'name' => 'Sweat Sticker','value' => 'Sweat Sticker'},
        'sticker_10' => {'name' => 'Unicorn Sticker','value' => 'Unicorn Sticker'},
        'sticker_11' => {'name' => 'Palm Tree Sticker','value' => 'Palm Tree Sticker'},
        'sticker_12' => {'name' => 'Radio Doodle Sticker','value' => 'Radio Doodle Sticker'},
        'sticker_13' => {'name' => 'Floating Sloth Sticker','value' => 'Floating Sloth Sticker'},
        'sticker_14' => {'name' => 'Sun Hat Sticker','value' => 'Sun Hat Sticker'},
        'sticker_15' => {'name' => 'Ice Cream Cone Sticker','value' => 'Ice Cream Cone Sticker'},
        'sticker_16' => {'name' => 'Palm Tree 2 Sticker','value' => 'Palm Tree 2 Sticker'},
        'sticker_17' => {'name' => 'Floating Flowers 2 Sticker','value' => 'Floating Flowers 2 Sticker'},
        'sticker_18' => {'name' => 'Wave Sticker','value' => 'Wave Sticker'},
        'sticker_19' => {'name' => 'Swim Fins Sticker','value' => 'Swim Fins Sticker'},
        'sticker_20' => {'name' => 'Kite Sticker','value' => 'Kite Sticker'},
        'sticker_21' => {'name' => 'Popsicle Sticker','value' => 'Popsicle Sticker'},
        'sticker_22' => {'name' => 'Sun Sticker','value' => 'Sun Sticker'},
        'sticker_23' => {'name' => 'Flamingo Sticker','value' => 'Flamingo Sticker'},
        'sticker_24' => {'name' => 'Visor Sticker','value' => 'Visor Sticker'},
        'sticker_25' => {'name' => 'Sun Face Sticker','value' => 'Sun Face Sticker'},
        'sticker_26' => {'name' => 'Scuba Mask Sticker','value' => 'Scuba Mask Sticker'},
        'sticker_27' => {'name' => 'Sand Castle Sticker','value' => 'Sand Castle Sticker'},
        'sticker_28' => {'name' => 'Watermelon Sticker','value' => 'Watermelon Sticker'},
        'sticker_29' => {'name' => 'Mermaid Tail Sticker','value' => 'Mermaid Tail Sticker'},
        'sticker_30' => {'name' => 'Beachball 2 Sticker','value' => 'Beachball 2 Sticker'},
        'sticker_31' => {'name' => 'Sunglasses Frogskin Sticker','value' => 'Sunglasses Frogskin Sticker'},
        'sticker_32' => {'name' => 'Beach Umbrella Sticker','value' => 'Beach Umbrella Sticker'},
        'sticker_33' => {'name' => 'Water Bubbles Sticker','value' => 'Water Bubbles Sticker'},
        'sticker_34' => {'name' => 'Flip Flops 2 Sticker','value' => 'Flip Flops 2 Sticker'},
        'sticker_35' => {'name' => 'Plane Sticker','value' => 'Plane Sticker'},
        'sticker_36' => {'name' => 'Mermaid Girl Sticker','value' => 'Mermaid Girl Sticker'},
        'sticker_37' => {'name' => 'Sundae Sticker','value' => 'Sundae Sticker'},
        'sticker_38' => {'name' => 'Trailer Sticker','value' => 'Trailer Sticker'},
        'sticker_39' => {'name' => 'Fan Summer Sticker','value' => 'Fan Summer Sticker'},
        'sticker_40' => {'name' => 'Surfboard Sticker','value' => 'Surfboard Sticker'},
        'sticker_41' => {'name' => 'Ice Cream Tub Sticker','value' => 'Ice Cream Tub Sticker'},
        'sticker_42' => {'name' => 'Rainbow 2 Sticker','value' => 'Rainbow 2 Sticker'},
        'sticker_43' => {'name' => 'Unicorn Float Sticker','value' => 'Unicorn Float Sticker'},
        'sticker_44' => {'name' => 'Volleyball Sticker','value' => 'Volleyball Sticker'},
        'sticker_45' => {'name' => 'Dolphin Doodle Sticker','value' => 'Dolphin Doodle Sticker'},
        'sticker_46' => {'name' => 'Mermaid Tail Water Sticker','value' => 'Mermaid Tail Water Sticker'},
        'sticker_47' => {'name' => 'Travel Car Bug Sticker','value' => 'Travel Car Bug Sticker'},
        'sticker_48' => {'name' => 'Soda Straw Sticker','value' => 'Soda Straw Sticker'},
        'sticker_49' => {'name' => 'BBQ Sticker','value' => 'BBQ Sticker'},
        'sticker_50' => {'name' => 'Travel Car Woody Sticker','value' => 'Travel Car Woody Sticker'}
    },
    'sticker_tab_2' => {
        'sticker_0' => {'name' => 'Reinvent Memories Sticker','value' => 'Reinvent Memories Sticker'},
        'sticker_1' => {'name' => 'HP White Sticker','value' => 'HP White Sticker'}
    },
    'sticker_tab_3' => {
        'sticker_0' => {'name' => 'Aviator Glasses Color Sticker','value' =>'Aviator Glasses Color Sticker'},
        'sticker_1' => {'name' => 'Bunny Ears Flowers Sticker','value' =>'Bunny Ears Flowers Sticker'},
        'sticker_2' => {'name' => 'Rabbit Mask Sticker','value' =>'Rabbit Mask Sticker'},
        'sticker_3' => {'name' => 'Sun Hat Sticker','value' =>'Sun Hat Sticker'},
        'sticker_4' => {'name' => 'Panda Mask Sticker','value' =>'Panda Mask Sticker'},
        'sticker_5' => {'name' => 'Beard Sticker','value' =>'Beard Sticker'},
        'sticker_6' => {'name' => 'Lips Sticker','value' =>'Lips Sticker'},
        'sticker_7' => {'name' => 'Cat Ears Sticker','value' =>'Cat Ears Sticker'},
        'sticker_8' => {'name' => 'Cat Whiskers Sticker','value' =>'Cat Whiskers Sticker'},
        'sticker_9' => {'name' => 'Derby Sticker','value' =>'Derby Sticker'},
        'sticker_10' => {'name' => 'Devil Horns Sticker','value' =>'Devil Horns Sticker'},
        'sticker_11' => {'name' => 'Glasses Football Sticker','value' =>'Glasses Football Sticker'},
        'sticker_12' => {'name' => 'Cat Glasses Sticker','value' =>'Cat Glasses Sticker'},
        'sticker_13' => {'name' => 'Crown Sticker','value' =>'Crown Sticker'},
        'sticker_14' => {'name' => 'Birthday Hat Sticker','value' =>'Birthday Hat Sticker'},
        'sticker_15' => {'name' => 'Glasses Red Sticker','value' =>'Glasses Red Sticker'},
        'sticker_16' => {'name' => 'Sunglasses Sticker','value' =>'Sunglasses Sticker'},
        'sticker_17' => {'name' => 'Glasses 1 Sticker','value' =>'Glasses 1 Sticker'},
        'sticker_18' => {'name' => 'Sunglasses Frogskin Sticker','value' =>'Sunglasses Frogskin Sticker'},
        'sticker_19' => {'name' => 'Party Hat Sticker','value' =>'Party Hat Sticker'},
        'sticker_20' => {'name' => 'Glasses Blinds Sticker','value' =>'Glasses Blinds Sticker'},
        'sticker_21' => {'name' => 'Mustache Brown Sticker','value' =>'Mustache Brown Sticker'},
        'sticker_22' => {'name' => 'Glasses Sticker','value' =>'Glasses Sticker'},
        'sticker_23' => {'name' => 'Aviator Glasses Sticker','value' =>'Aviator Glasses Sticker'},
        'sticker_24' => {'name' => 'Glasses Blossom Sticker','value' =>'Glasses Blossom Sticker'},
        'sticker_25' => {'name' => 'Cat on Head Sticker','value' =>'Cat on Head Sticker'},
        'sticker_26' => {'name' => 'Mustache Dark Sticker','value' =>'Mustache Dark Sticker'}
    },
    'sticker_tab_4' => {
        'sticker_0' => {'name' => 'Heart Garland Sticker','value' =>'Heart Garland Sticker'},
        'sticker_1' => {'name' => 'Stars Bunch Sticker','value' =>'Stars Bunch Sticker'},
        'sticker_2' => {'name' => '3D diamond 2 Sticker','value' =>'3D diamond 2 Sticker'},
        'sticker_3' => {'name' => 'Unicorn Sticker','value' =>'Unicorn Sticker'},
        'sticker_4' => {'name' => 'Heart Arrow Sticker','value' =>'Heart Arrow Sticker'},
        'sticker_5' => {'name' => 'Skull Sticker','value' =>'Skull Sticker'},
        'sticker_6' => {'name' => 'Hearts Sticker','value' =>'Hearts Sticker'},
        'sticker_7' => {'name' => 'Xoxo Sticker','value' =>'Xoxo Sticker'},
        'sticker_8' => {'name' => 'Feather Sticker','value' =>'Feather Sticker'},
        'sticker_9' => {'name' => 'Heart Wings Sticker','value' =>'Heart Wings Sticker'},
        'sticker_10' => {'name' => 'Arrow Sticker','value' =>'Arrow Sticker'},
        'sticker_11' => {'name' => 'LOL Sticker','value' =>'LOL Sticker'},
        'sticker_12' => {'name' => 'Heart 2 Sticker','value' =>'Heart 2 Sticker'},
        'sticker_13' => {'name' => 'Diamond Sticker','value' =>'Diamond Sticker'},
        'sticker_14' => {'name' => 'Peace Sticker','value' =>'Peace Sticker'},
        'sticker_15' => {'name' => 'Smiley Sticker','value' =>'Smiley Sticker'},
        'sticker_16' => {'name' => 'Feather 2 Sticker','value' =>'Feather 2 Sticker'},
        'sticker_17' => {'name' => 'OMG Sticker','value' =>'OMG Sticker'},
        'sticker_18' => {'name' => 'Hearts Doodle Sticker','value' =>'Hearts Doodle Sticker'},
        'sticker_19' => {'name' => 'Banner Sticker','value' =>'Banner Sticker'},
        'sticker_20' => {'name' => 'Thumbs Up Sticker','value' =>'Thumbs Up Sticker'},
        'sticker_21' => {'name' => 'Heart Sticker','value' =>'Heart Sticker'},
        'sticker_22' => {'name' => 'Football Sticker','value' =>'Football Sticker'},
        'sticker_23' => {'name' => 'Heart Express Sticker','value' =>'Heart Express Sticker'},
        'sticker_24' => {'name' => '3D diamond 1 Sticker','value' =>'3D diamond 1 Sticker'},
        'sticker_25' => {'name' => 'Fist Sticker','value' =>'Fist Sticker'},
        'sticker_26' => {'name' => 'Heart Pixel Sticker','value' =>'Heart Pixel Sticker'},
        'sticker_27' => {'name' => 'Word Cloud Grumble Sticker','value' =>'Word Cloud Grumble Sticker'}
    },
    'sticker_tab_5' => {
        'sticker_0' => {'name' => 'Frappuccino Sticker','value' =>'Frappuccino Sticker'},
        'sticker_1' => {'name' => 'Pineapple Sticker','value' =>'Pineapple Sticker'},
        'sticker_2' => {'name' => 'Cupcake Sticker','value' =>'Cupcake Sticker'},
        'sticker_3' => {'name' => 'Cat Fries Sticker','value' =>'Cat Fries Sticker'},
        'sticker_4' => {'name' => 'BBQ Sticker','value' =>'BBQ Sticker'},
        'sticker_5' => {'name' => 'Pie Sticker','value' =>'Pie Sticker'},
        'sticker_6' => {'name' => 'Doughnut Sticker','value' =>'Doughnut Sticker'},
        'sticker_7' => {'name' => 'Bacon n egg Sticker','value' =>'Bacon n egg Sticker'},
        'sticker_8' => {'name' => 'Sundae Sticker','value' =>'Sundae Sticker'},
        'sticker_9' => {'name' => 'Ketchup Hot Dog Sticker','value' =>'Ketchup Hot Dog Sticker'},
        'sticker_10' => {'name' => 'Soda Sticker','value' =>'Soda Sticker'},
        'sticker_11' => {'name' => 'Pizza Sticker','value' =>'Pizza Sticker'},
        'sticker_12' => {'name' => 'Soda Can Sticker','value' =>'Soda Can Sticker'},
        'sticker_13' => {'name' => 'Valentines Cupcake Sticker','value' =>'Valentines Cupcake Sticker'},
        'sticker_14' => {'name' => 'Apple Angry Sticker','value' =>'Apple Angry Sticker'},
        'sticker_15' => {'name' => 'Turkey Sticker','value' =>'Turkey Sticker'},
        'sticker_16' => {'name' => 'Taco 2 Sticker','value' =>'Taco 2 Sticker'},
        'sticker_17' => {'name' => 'Ice Cream Cone Sticker','value' =>'Ice Cream Cone Sticker'},
        'sticker_18' => {'name' => 'Ice Cream Tub Sticker','value' =>'Ice Cream Tub Sticker'},
        'sticker_19' => {'name' => 'Spoon Sticker','value' =>'Spoon Sticker'},
        'sticker_20' => {'name' => 'Cocoa Sticker','value' =>'Cocoa Sticker'},
        'sticker_21' => {'name' => 'Watermelon Sticker','value' =>'Watermelon Sticker'},
        'sticker_22' => {'name' => 'Candy Sticker','value' =>'Candy Sticker'},
        'sticker_23' => {'name' => 'Cat Coffee Sticker','value' =>'Cat Coffee Sticker'},
        'sticker_24' => {'name' => 'Fork Sticker','value' =>'Fork Sticker'},
        'sticker_25' => {'name' => 'Oranges Sticker','value' =>'Oranges Sticker'}
    },
    'sticker_tab_6' => {
        'sticker_0' => {'name' => 'Balloons 2 Sticker','value' =>'Balloons 2 Sticker'},
        'sticker_1' => {'name' => 'Cupcake Sticker','value' =>'Cupcake Sticker'},
        'sticker_2' => {'name' => 'Party Hat Sticker','value' =>'Party Hat Sticker'},
        'sticker_3' => {'name' => 'Banner Sticker','value' =>'Banner Sticker'},
        'sticker_4' => {'name' => 'Fireworks Sticker','value' =>'Fireworks Sticker'},
        'sticker_5' => {'name' => 'Stars Sticker','value' =>'Stars Sticker'},
        'sticker_6' => {'name' => 'Birthday Hat Sticker','value' =>'Birthday Hat Sticker'},
        'sticker_7' => {'name' => 'Gift Sticker','value' =>'Gift Sticker'},
        'sticker_8' => {'name' => 'Balloons Sticker','value' =>'Balloons Sticker'},
        'sticker_9' => {'name' => 'Cake Sticker','value' =>'Cake Sticker'},
        'sticker_10' => {'name' => 'Gift Dog Sticker','value' =>'Gift Dog Sticker'},
        'sticker_11' => {'name' => 'Cat Celebrate Sticker','value' =>'Cat Celebrate Sticker'},
        'sticker_12' => {'name' => 'Crown Sticker','value' =>'Crown Sticker'},
        'sticker_13' => {'name' => 'Horn Sticker','value' =>'Horn Sticker'}
    },
    'sticker_tab_7' => {
        'sticker_0' => {'name' => 'Cat Face Sticker','value' =>'Cat Face Sticker'},
        'sticker_1' => {'name' => 'Fox Sticker','value' =>'Fox Sticker'},
        'sticker_2' => {'name' => 'Rabbit Sticker','value' =>'Rabbit Sticker'},
        'sticker_3' => {'name' => 'Cat Fries Sticker','value' =>'Cat Fries Sticker'},
        'sticker_4' => {'name' => 'Cat Sticker','value' =>'Cat Sticker'},
        'sticker_5' => {'name' => 'Hedgehog Sticker','value' =>'Hedgehog Sticker'},
        'sticker_6' => {'name' => 'Scary Cat Sticker','value' =>'Scary Cat Sticker'},
        'sticker_7' => {'name' => 'Spider Sticker','value' =>'Spider Sticker'},
        'sticker_8' => {'name' => 'Dog Sticker','value' =>'Dog Sticker'},
        'sticker_9' => {'name' => 'Owl Sticker','value' =>'Owl Sticker'},
        'sticker_10' => {'name' => 'Cat on Head Sticker','value' =>'Cat on Head Sticker'},
        'sticker_11' => {'name' => 'Bird Envelope Sticker','value' =>'Bird Envelope Sticker'},
        'sticker_12' => {'name' => 'Sloth Sticker','value' =>'Sloth Sticker'},
        'sticker_13' => {'name' => 'Panda Sticker','value' =>'Panda Sticker'},
        'sticker_14' => {'name' => 'Cat Shock Sticker','value' =>'Cat Shock Sticker'},
        'sticker_15' => {'name' => 'Butterfly Sticker','value' =>'Butterfly Sticker'},
        'sticker_16' => {'name' => 'Bird Sticker','value' =>'Bird Sticker'},
        'sticker_17' => {'name' => 'Koala Sticker','value' =>'Koala Sticker'},
        'sticker_18' => {'name' => 'Cat Grumble Sticker','value' =>'Cat Grumble Sticker'},
        'sticker_19' => {'name' => 'Pig Sticker','value' =>'Pig Sticker'}
    },
    'sticker_tab_8' => {
        'sticker_0' => {'name' => 'Feather Sticker','value' =>'Feather Sticker'},
        'sticker_1' => {'name' => 'Rainbow 2 Sticker','value' =>'Rainbow 2 Sticker'},
        'sticker_2' => {'name' => 'Flowers Sticker','value' =>'Flowers Sticker'},
        'sticker_3' => {'name' => 'Moon Sticker','value' =>'Moon Sticker'},
        'sticker_4' => {'name' => 'Feather 2 Sticker','value' =>'Feather 2 Sticker'},
        'sticker_5' => {'name' => 'Hibiscus Sticker','value' =>'Hibiscus Sticker'},
        'sticker_6' => {'name' => 'Sun Sticker','value' =>'Sun Sticker'},
        'sticker_7' => {'name' => 'Heart Bouquet Sticker','value' =>'Heart Bouquet Sticker'},
        'sticker_8' => {'name' => 'Mushrooms Sticker','value' =>'Mushrooms Sticker'},
        'sticker_9' => {'name' => 'Flowers Sticker','value' =>'Flowers Sticker'},
        'sticker_10' => {'name' => 'Plum Blossom Sticker','value' =>'Plum Blossom Sticker'},
        'sticker_11' => {'name' => 'Sun Face Sticker','value' =>'Sun Face Sticker'},
        'sticker_12' => {'name' => 'Star Sticker','value' =>'Star Sticker'},
        'sticker_13' => {'name' => 'Cloud Sun Sticker','value' =>'Cloud Sun Sticker'},
        'sticker_14' => {'name' => 'Leaves Sticker','value' =>'Leaves Sticker'},
        'sticker_15' => {'name' => 'Rosebud Sticker','value' =>'Rosebud Sticker'},
        'sticker_16' => {'name' => 'Palm Tree Sticker','value' =>'Palm Tree Sticker'},
        'sticker_17' => {'name' => 'Stars Sticker','value' =>'Stars Sticker'},
        'sticker_18' => {'name' => 'Cloud Angry Sticker','value' =>'Cloud Angry Sticker'},
        'sticker_19' => {'name' => 'Palm Tree 2 Sticker','value' =>'Palm Tree 2 Sticker'},
        'sticker_20' => {'name' => 'Wave Sticker','value' =>'Wave Sticker'},
        'sticker_21' => {'name' => 'Star Yellow Sticker','value' =>'Star Yellow Sticker'},
        'sticker_22' => {'name' => 'Cloud Sad Sticker','value' =>'Cloud Sad Sticker'}
    },
    'sticker_tab_9' => {
        'sticker_0' => {'name' => 'Band aid 2 Sticker','value' =>'Band aid 2 Sticker'},
        'sticker_1' => {'name' => 'Letter Sticker','value' =>'Letter Sticker'},
        'sticker_2' => {'name' => 'Kleenex Sticker','value' =>'Kleenex Sticker'},
        'sticker_3' => {'name' => 'Measles Sticker','value' =>'Measles Sticker'},
        'sticker_4' => {'name' => 'Medicine Sticker','value' =>'Medicine Sticker'},
        'sticker_5' => {'name' => 'Love Monster Sticker','value' =>'Love Monster Sticker'}
    }

}

$frame ={
    'frame_0' => {'name' => 'Hearts Overlay Frame','value' =>'HeartsOverlayFrame'},
    'frame_1' => {'name' => 'Sloppy Frame','value' =>'SloppyFrame'},
    'frame_2' => {'name' => 'Rainbow Frame','value' =>'RainbowFrame'},
    'frame_3' => {'name' => 'White Frame','value' =>'WhiteFrame'},
    'frame_4' => {'name' => 'Stars Overlay Frame','value' =>'StarsOverlayFrame'},
    'frame_5' => {'name' => 'Polka Dots Frame','value' =>'PolkadotsFrame'},
    'frame_5' => {'name' => 'LOreal iOS Frame','value' =>'LOreal_iOS_1c'},
    'frame_6' => {'name' => 'Nestle iOS Frame','value' =>'Nestle_iOS_Frame'},
    'frame_7' => {'name' => 'San Pelegrino iOS Frame','value' =>'S_pellegrino_iOS_Frame'},
    'frame_8' => {'name' => 'Grey Shadow Frame','value' =>'GreyShadowFrame'},
    'frame_9' => {'name' => 'Pink Triangle Frame','value' =>'PinkTriangleFrame'},
    'frame_10' => {'name' => 'White Rounded Frame','value' =>'WhiteRoundedFrame'},
    'frame_11' => {'name' => 'Floral 2 Frame','value' =>'Floral2Frame'},
    'frame_12' => {'name' => 'Blue Watercolor Frame','value' =>'BlueWatercoloFrame'},
    'frame_13' => {'name' => 'Floral Overlay Frame','value' =>'FloralOverlayFrame'},
    'frame_14' => {'name' => 'Red Frame','value' =>'RedFrame'},
    'frame_15' => {'name' => 'Gradient Frame','value' =>'GradientFrame'},
    'frame_16' => {'name' => 'Turquoise Frame','value' =>'TurquoiseFrame'},
    'frame_17' => {'name' => 'Dots Overlay Frame','value' =>'DotsOverlayFrame'},
    'frame_18' => {'name' => 'Kraft Frame','value' =>'KraftFrame'},
    'frame_19' => {'name' => 'White Bar Frame','value' =>'WhiteBarFrame'},
    'frame_20' => {'name' => 'Pink Spray Paint Frame','value' =>'PinkSpraypaintFrame'},
    'frame_21' => {'name' => 'White Full Frame','value' =>'WhiteFullFrame'}
}
$font ={
    'font_0' => {'name' => 'Aleo','value' =>'Aleo'},
    'font_1' => {'name' => 'BERNIER Regular','value' =>'BERNIERRegular-Regular'},
    'font_2' => {'name' => 'Blogger Sans','value' =>'BloggerSans-Light'},
    'font_3' => {'name' => 'Cheque','value' =>'Cheque-Regular'},
    'font_4' => {'name' => 'Fira Sans','value' =>'FiraSans-Regular'},
    'font_5' => {'name' => 'Gagalin','value' =>'Gagalin-Regular'},
    'font_6' => {'name' => 'Hagin Caps Thin','value' =>'Hagin'},
    'font_7' => {'name' => 'Panton','value' =>'Panton-LightitalicCaps'},
    'font_8' => {'name' => 'Panton','value' =>'Panton-LightitalicCaps'},
    'font_9' => {'name' => 'Perfograma','value' =>'Perfograma'},
    'font_10' => {'name' => 'Summer Font','value' =>'SummerFont-Light'},
    'font_11' => {'name' => 'American Typewriter','value' =>'American'},
    'font_12' => {'name' => 'Baskerville','value' =>'Baskerville'},
    'font_13' => {'name' => 'Bodoni 72','value' =>'BodoniSvtyTwoITCTT-Book'},
    'font_14' => {'name' => 'Bradley Hand','value' =>'Bradley'},
    'font_15' => {'name' => 'Chalkboard SE','value' =>'ChalkboardSE-Regular'},
    'font_16' => {'name' => 'DIN Alternate','value' =>'DIN'},
    'font_17' => {'name' => 'Helvetica Neue','value' =>'Helvetica'},
    'font_18' => {'name' => 'Noteworthy','value' =>'Noteworthy-Light'},
    'font_19' => {'name' => 'Snell Roundhand','value' =>'Snell'},
    'font_20' => {'name' => 'Thonburi','value' =>'Thonburi'}

}